version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
notify:
   webhooks:
     - url: https://hooks.ringcentral.com/webhook/v2/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdCI6ImMiLCJvaSI6IjQ0NDY2MTc3IiwiaWQiOiIyMzM1OTk3OTc5In0.nJnSdD3d2ODrbt4cjamuiYDq2X5CeYwLRRMUMH0nGI8
